# Generated by Django 5.2.4 on 2025-10-29 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_post_media_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='impression',
            name='viewed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddIndex(
            model_name='impression',
            index=models.Index(fields=['user', 'viewed_at'], name='content_imp_user_id_a3a5b4_idx'),
        ),
    ]
